OTONAL_HARMONY_NAME = "I"
UTONAL_HARMONY_NAME = "1divI"
F_OTONAL_HARMONY_NAME = "f(I)"
F_UTONAL_HARMONY_NAME = "f(1divI)"

DEFAULT_N_GRADATIONS_PER_TRANSITION = 4
MIN_TRANSITION_CHANGE = 0.75
MAX_TRANSITION_CHANGE = 1.4
