# """
COMPUTE_FAMILIES_PITCH = False
COMPUTE_STOCHASTIC_PARTS = False
COMPUTE_COMMON_HARMONICS = False
COMPUTE_CENGKOK = False
COMPUTE_THE_THIRD_WAY = False
COMPUTE_DRONE = False

COMPUTE_SUSTAINING_INSTRUMENT_0_STOCHASTIC_PART = False
COMPUTE_SUSTAINING_INSTRUMENT_1_STOCHASTIC_PART = False
COMPUTE_SUSTAINING_INSTRUMENT_2_STOCHASTIC_PART = False
COMPUTE_KEYBOARD_STOCHASTIC_PART = False
COMPUTE_PILLOW_STOCHASTIC_PART = False
COMPUTE_GONG_STOCHASTIC_PART = False

RENDER_PILLOW = False
RENDER_SINES = False
RENDER_DRONE = False

RENDER_SOUNDFILES = False
RENDER_MIDIFILES = False
RENDER_NOTATION = True
RENDER_VIDEOS = False
# """


"""
COMPUTE_FAMILIES_PITCH = True
COMPUTE_STOCHASTIC_PARTS = True
COMPUTE_COMMON_HARMONICS = True
COMPUTE_CENGKOK = True
COMPUTE_THE_THIRD_WAY = True
COMPUTE_DRONE = True

COMPUTE_SUSTAINING_INSTRUMENT_0_STOCHASTIC_PART = True
COMPUTE_SUSTAINING_INSTRUMENT_1_STOCHASTIC_PART = True
COMPUTE_SUSTAINING_INSTRUMENT_2_STOCHASTIC_PART = True
COMPUTE_KEYBOARD_STOCHASTIC_PART = True
COMPUTE_PILLOW_STOCHASTIC_PART = True
COMPUTE_GONG_STOCHASTIC_PART = True

RENDER_PILLOW = True
RENDER_SINES = True
RENDER_DRONE = True

RENDER_SOUNDFILES = True
RENDER_MIDIFILES = True
RENDER_NOTATION = True
RENDER_VIDEOS = False
"""
